// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateResponse struct {
	ID           string `json:"ID"`
	ResponseCode int    `json:"ResponseCode"`
}

type DeleteResponse struct {
	ResponseCode int `json:"ResponseCode"`
}

type Product struct {
	ID   string `json:"ID"`
	Name string `json:"Name"`
}

type ReadResponse struct {
	Products     []*Product `json:"Products"`
	ResponseCode int        `json:"ResponseCode"`
}

type UpdateResponse struct {
	ID           string `json:"ID"`
	Name         string `json:"Name"`
	ResponseCode int    `json:"ResponseCode"`
}
